services:
  db:
    image: postgres:15
    container_name: brofu
    restart: always
    ports:
    - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - settings.env

volumes:
  postgres_data: