"""initial migration

Revision ID: ec8b47333372
Revises:
Create Date: 2025-08-12 23:10:17.954431

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ec8b47333372"
down_revision: Union[str, None] = "8e05f4de7c5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('players_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "nationality", sa.VARCHAR(length=3), autoincrement=False, nullable=True
        ),
        sa.Column("date_of_birth", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column(
            "sub_position", sa.VARCHAR(length=3), autoincrement=False, nullable=True
        ),
        sa.Column("position", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="players_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "levels",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('levels_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("team", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "season", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "logo_url", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="levels_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "level_players",
        sa.Column("level_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("player_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["levels.id"],
            name=op.f("level_players_level_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("level_players_player_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "level_id", "player_id", name=op.f("level_players_pkey")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("level_players")
    op.drop_table("levels")
    op.drop_table("players")
    # ### end Alembic commands ###
